{% set name = "torchquad" %}
{% set org = "esa" %}
{% set version = "0.4.1" %}
{% set sha256 = "bcd4c700ffe25059b74202c552e2f661ac0bcf161cff5e5f03835214c394a20c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - matplotlib-base >=3.3.3
    - loguru >=0.5.3
    - autoray >=0.5.0
    - numpy
    - scipy >=1.6.0
    - tqdm >=4.56.0

test:
  imports:
    - torchquad
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/esa/torchquad/
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  summary: torchquad provides torch-based numerical integration methods.
  description: |
    This project allows utilizing GPUs for efficient numerical 
    integration with PyTorch. It  is designed for the machine learning 
    community and research groups focusing on topics requiring high-dimensional 
    integration. By using PyTorch backpropagation through the integrals is possible.
  doc_url: https://torchquad.readthedocs.io/en/release/
  dev_url: https://github.com/esa/torchquad/

extra:
  recipe-maintainers:
    - gomezzz
